openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Сервис загрузки информации о стене пользователя
servers:
  - url: http://localhost:8082
    description: Page service
paths:
  /load_info:
    get:
      summary: Загрузка информации со стены пользователя
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
     
      responses:
        '200':
          description: The pages for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages'
        404:
          description: No page found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
 
components:
  schemas:
    page_id:
      description: Уникальный идентификатор пользователя
      type: integer
    pages:
      type: array
      items:
        $ref: '#/components/schemas/page'
    page:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/page_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        lovely_books:
          type: string
        lovely_musics:
          type: string
        lovely_movies:
          type: string
        religion:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []
