openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'API P2PService'
  description: API пересылки и записи сообщений
servers:
  - url: http://localhost:8081
    description: P2P server
paths:
  /send_msg:
    post:
      summary: Отправка сообщения
      parameters:
      - name: id_to
        description: Уникальный идентификатор получателя
        in: query
        required: true
        schema:
          type: integer
      - name: message
        description: Текст сообщения
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The  message was sent
        404:
          description: Error with sending  message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    messages:
      type: array
      items:
        $ref: '#/components/schemas/message'
    message:
      type: object
      required:
        - date
        - id
        - id_to
        - id_from
        - message
      properties:
        date:
          type: string
        id:
          type: integer
        id_to:
          type: integer
        id_from:
          type: integer
        message:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []